# Generated by Django 3.1.6 on 2021-02-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, unique=True)),
                ('catalogue', models.CharField(max_length=500)),
                ('couverture', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
    ]
