# Generated by Django 3.1.6 on 2021-04-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='tarif',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
