# Generated by Django 3.1.6 on 2021-02-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0002_auto_20210222_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='pays',
            field=models.CharField(default='', max_length=200),
        ),
    ]
