# Generated by Django 3.1.6 on 2021-04-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0002_auto_20210421_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslider',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
