# Generated by Django 3.1.6 on 2021-04-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0003_carouselslider_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslider',
            name='date_d_ajout',
            field=models.DateField(auto_now=True),
        ),
    ]
