# Generated by Django 3.1.6 on 2021-02-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0003_film_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='couverture',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='film',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='annee',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='duree',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projection',
            name='tarif',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
