# Generated by Django 3.1.6 on 2021-02-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0004_auto_20210222_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='home_page',
            field=models.BooleanField(default=False),
        ),
    ]
