# Generated by Django 3.1.6 on 2021-04-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0004_carouselslider_date_d_ajout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselslider',
            options={'verbose_name': 'Images de carrousel'},
        ),
        migrations.AddField(
            model_name='projection',
            name='tarif_reduit',
            field=models.FloatField(blank=True, null=True, verbose_name='Tarif réduit'),
        ),
        migrations.AlterField(
            model_name='carouselslider',
            name='date_d_ajout',
            field=models.DateField(auto_now=True, verbose_name="Date d'ajout"),
        ),
    ]
