# Generated by Django 3.1.6 on 2021-02-22 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0005_catalogue_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
