# Generated by Django 3.1.6 on 2021-02-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0006_catalogue_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='catalogue',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='couverture',
        ),
        migrations.RemoveField(
            model_name='film',
            name='picture',
        ),
        migrations.AddField(
            model_name='catalogue',
            name='couv',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='lien',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
